# -*- coding: utf-8 -*-
"""
Enrich a WeChat-article XLSX with article body text and matched products.

The script reads an XLSX generated by wechat_album_export.py, fetches each URL,
extracts text from the WeChat article body, matches products from
yonyou_product_knowledge_base.csv, and writes a new XLSX with two extra columns:
"正文" and "产品".

Usage:
    python enrich_wechat_articles.py
    python enrich_wechat_articles.py --input 数智先锋_文章链接_含发布时间.xlsx
"""

from __future__ import annotations

import argparse
import csv
import html
import re
import sys
import time
import zipfile
from dataclasses import dataclass
from datetime import datetime, timezone
from html.parser import HTMLParser
from pathlib import Path
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen
from xml.etree import ElementTree as ET
from xml.sax.saxutils import escape


if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

DEFAULT_INPUT = "数智先锋_文章链接_含发布时间.xlsx"
DEFAULT_PRODUCTS = "yonyou_product_knowledge_base.csv"
DEFAULT_OUTPUT = "数智先锋_文章链接_含发布时间_含正文产品.xlsx"
HEADERS_TO_ADD = ["正文", "产品"]
SHEET_NAME = "文章链接"
EXCEL_CELL_LIMIT = 32767


@dataclass
class ProductRule:
    product: str
    category: str
    strong_terms: list[str]
    weak_terms: list[str]


class WeChatContentParser(HTMLParser):
    """Extract visible-ish text inside the #js_content element."""

    BLOCK_TAGS = {
        "address",
        "article",
        "aside",
        "blockquote",
        "div",
        "figcaption",
        "figure",
        "footer",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6",
        "li",
        "p",
        "section",
        "table",
        "td",
        "th",
        "tr",
        "ul",
        "ol",
    }
    VOID_TAGS = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.in_content = False
        self.depth = 0
        self.skip_depth = 0
        self.parts: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        attrs_dict = {name: value or "" for name, value in attrs}
        if not self.in_content and attrs_dict.get("id") == "js_content":
            self.in_content = True
            self.depth = 1
            return

        if not self.in_content:
            return

        if tag not in self.VOID_TAGS:
            self.depth += 1
        if tag in {"script", "style", "noscript"}:
            self.skip_depth += 1
        if tag == "br" or tag in self.BLOCK_TAGS:
            self._newline()
        if tag == "img":
            alt = (attrs_dict.get("alt") or "").strip()
            if alt and alt not in {"图片", "Image", "image"}:
                self.parts.append(alt)
                self._newline()

    def handle_endtag(self, tag: str) -> None:
        if not self.in_content:
            return

        if tag in self.BLOCK_TAGS:
            self._newline()
        if tag in {"script", "style", "noscript"} and self.skip_depth:
            self.skip_depth -= 1

        if tag not in self.VOID_TAGS:
            self.depth -= 1
            if self.depth <= 0:
                self.in_content = False

    def handle_data(self, data: str) -> None:
        if not self.in_content or self.skip_depth:
            return
        text = html.unescape(data)
        if text.strip():
            self.parts.append(text)

    def _newline(self) -> None:
        if not self.parts or self.parts[-1] != "\n":
            self.parts.append("\n")

    def text(self) -> str:
        raw = "".join(self.parts)
        lines = []
        for line in raw.splitlines():
            cleaned = re.sub(r"[ \t\r\f\v]+", " ", line).strip()
            if cleaned:
                lines.append(cleaned)
        return "\n".join(lines)


def read_xlsx(path: Path) -> list[list[str]]:
    with zipfile.ZipFile(path) as workbook:
        names = set(workbook.namelist())
        shared_strings = read_shared_strings(workbook) if "xl/sharedStrings.xml" in names else []
        sheet = ET.fromstring(workbook.read("xl/worksheets/sheet1.xml"))

    ns = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    rows: list[list[str]] = []
    for row in sheet.findall(".//m:sheetData/m:row", ns):
        cell_values: dict[int, str] = {}
        for cell in row.findall("m:c", ns):
            ref = cell.attrib.get("r", "")
            col_idx = column_index(ref)
            if col_idx is None:
                continue
            cell_values[col_idx] = read_cell_value(cell, shared_strings, ns)
        if cell_values:
            max_col = max(cell_values)
            rows.append([cell_values.get(i, "") for i in range(1, max_col + 1)])
    return rows


def read_shared_strings(workbook: zipfile.ZipFile) -> list[str]:
    ns = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
    root = ET.fromstring(workbook.read("xl/sharedStrings.xml"))
    values = []
    for item in root.findall("m:si", ns):
        values.append("".join(text.text or "" for text in item.findall(".//m:t", ns)))
    return values


def read_cell_value(cell: ET.Element, shared_strings: list[str], ns: dict[str, str]) -> str:
    cell_type = cell.attrib.get("t")
    if cell_type == "inlineStr":
        return "".join(text.text or "" for text in cell.findall(".//m:t", ns))

    value = cell.find("m:v", ns)
    if value is None or value.text is None:
        return ""
    if cell_type == "s":
        return shared_strings[int(value.text)]
    return value.text


def column_index(cell_ref: str) -> int | None:
    match = re.match(r"([A-Z]+)", cell_ref)
    if not match:
        return None
    total = 0
    for char in match.group(1):
        total = total * 26 + ord(char) - 64
    return total


def load_product_rules(path: Path) -> list[ProductRule]:
    rules: list[ProductRule] = []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            product = (row.get("产品") or "").strip()
            if not product:
                continue
            aliases = split_terms(row.get("产品别名") or "")
            keywords = split_terms(row.get("关键词") or "")
            modules = split_terms(row.get("功能模块") or "")
            strong_terms = unique_terms([product, *aliases])
            weak_terms = unique_terms([*keywords, *modules])
            rules.append(
                ProductRule(
                    product=product,
                    category=(row.get("分类") or "").strip(),
                    strong_terms=strong_terms,
                    weak_terms=weak_terms,
                )
            )
    return rules


def split_terms(value: str) -> list[str]:
    return [term.strip() for term in re.split(r"[,，、;；/\n]+", value) if term.strip()]


def unique_terms(terms: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for term in terms:
        key = term.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(term)
    return result


GENERIC_WEAK_TERMS = {
    "ai",
    "bi",
    "erp",
    "saas",
    "财务",
    "人力",
    "供应链",
    "采购",
    "制造",
    "营销",
    "协同",
    "数据",
    "数智化",
    "企业数字化",
    "报表",
}


def match_products(title: str, body: str, rules: list[ProductRule]) -> str:
    context = f"{title}\n{body}".lower()
    scored: list[tuple[float, int, str]] = []

    for rule in rules:
        score = 0.0
        strong_hits = 0
        weak_distinct_hits = 0

        for term in rule.strong_terms:
            hits = count_term(context, term)
            if hits:
                strong_hits += hits
                score += hits * (10 + min(len(term), 12) * 0.2)

        for term in rule.weak_terms:
            hits = count_term(context, term)
            if hits:
                weak_distinct_hits += 1
                normalized = term.lower()
                if normalized in GENERIC_WEAK_TERMS:
                    score += min(hits, 3) * 0.4
                elif len(normalized) <= 2:
                    score += min(hits, 3) * 1.0
                else:
                    score += min(hits, 4) * 2.0

        if strong_hits or (score >= 8 and weak_distinct_hits >= 2):
            scored.append((score, strong_hits, rule.product))

    scored.sort(key=lambda item: (item[0], item[1], len(item[2])), reverse=True)
    selected = [product for score, _strong, product in scored if score >= 3][:3]
    return "；".join(selected)


def count_term(context: str, term: str) -> int:
    needle = term.strip().lower()
    if not needle:
        return 0
    if re.fullmatch(r"[a-z0-9+#.]+", needle):
        return len(re.findall(rf"(?<![a-z0-9]){re.escape(needle)}(?![a-z0-9])", context))
    return context.count(needle)


def fetch_article_body(url: str, timeout: int) -> str:
    request = Request(
        url,
        headers={
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "User-Agent": (
                "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) "
                "AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 "
                "MicroMessenger/8.0"
            ),
        },
    )
    with urlopen(request, timeout=timeout) as response:
        html_text = response.read().decode("utf-8", errors="replace")

    parser = WeChatContentParser()
    parser.feed(html_text)
    parser.close()
    return parser.text()


def excel_text(value: object) -> str:
    text = str(value)
    cleaned = "".join(char if char in "\t\n\r" or ord(char) >= 32 else " " for char in text)
    if len(cleaned) > EXCEL_CELL_LIMIT:
        return cleaned[: EXCEL_CELL_LIMIT - 20] + "\n[内容超长已截断]"
    return cleaned


def cell_ref(col_idx: int, row_idx: int) -> str:
    letters = ""
    n = col_idx
    while n:
        n, rem = divmod(n - 1, 26)
        letters = chr(65 + rem) + letters
    return f"{letters}{row_idx}"


def cell_xml(value: object, col_idx: int, row_idx: int) -> str:
    ref = cell_ref(col_idx, row_idx)
    return f'<c r="{ref}" t="inlineStr"><is><t xml:space="preserve">{escape(excel_text(value))}</t></is></c>'


def write_xlsx(path: Path, rows: list[list[str]]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_name(path.stem + ".tmp.xlsx")
    all_rows = rows
    sheet_rows = []
    for row_idx, row in enumerate(all_rows, 1):
        cells = "".join(cell_xml(value, col_idx, row_idx) for col_idx, value in enumerate(row, 1))
        sheet_rows.append(f'<row r="{row_idx}">{cells}</row>')

    last_col = cell_ref(len(all_rows[0]), 1).rstrip("1") if all_rows else "A"
    sheet_xml = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>
  <sheetFormatPr defaultRowHeight="15"/>
  <cols>
    <col min="1" max="1" width="60" customWidth="1"/>
    <col min="2" max="2" width="110" customWidth="1"/>
    <col min="3" max="3" width="16" customWidth="1"/>
    <col min="4" max="4" width="22" customWidth="1"/>
    <col min="5" max="5" width="90" customWidth="1"/>
    <col min="6" max="6" width="28" customWidth="1"/>
  </cols>
  <sheetData>{''.join(sheet_rows)}</sheetData>
  <autoFilter ref="A1:{last_col}{len(all_rows)}"/>
</worksheet>'''

    content_types = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
  <Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>
  <Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>
</Types>'''
    rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>
  <Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/>
</Relationships>'''
    workbook = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets><sheet name="{escape(SHEET_NAME)}" sheetId="1" r:id="rId1"/></sheets>
</workbook>'''
    workbook_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>'''
    core = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <dc:creator>Codex</dc:creator><cp:lastModifiedBy>Codex</cp:lastModifiedBy><dcterms:modified xsi:type="dcterms:W3CDTF">{datetime.now(timezone.utc):%Y-%m-%dT%H:%M:%SZ}</dcterms:modified>
</cp:coreProperties>'''
    app = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">
  <Application>Codex</Application>
</Properties>'''

    with zipfile.ZipFile(temp_path, "w", zipfile.ZIP_DEFLATED) as workbook_zip:
        workbook_zip.writestr("[Content_Types].xml", content_types)
        workbook_zip.writestr("_rels/.rels", rels)
        workbook_zip.writestr("xl/workbook.xml", workbook)
        workbook_zip.writestr("xl/_rels/workbook.xml.rels", workbook_rels)
        workbook_zip.writestr("xl/worksheets/sheet1.xml", sheet_xml)
        workbook_zip.writestr("docProps/core.xml", core)
        workbook_zip.writestr("docProps/app.xml", app)

    try:
        temp_path.replace(path)
        return path
    except PermissionError:
        fallback = path.with_name(f"{path.stem}_{datetime.now():%Y%m%d_%H%M%S}{path.suffix}")
        temp_path.replace(fallback)
        return fallback


def enrich_rows(input_rows: list[list[str]], rules: list[ProductRule], timeout: int, sleep_seconds: float) -> list[list[str]]:
    if not input_rows:
        raise RuntimeError("Input XLSX is empty")

    headers = list(input_rows[0])
    for header in HEADERS_TO_ADD:
        if header not in headers:
            headers.append(header)

    url_idx = headers.index("url")
    title_idx = headers.index("标题")
    body_idx = headers.index("正文")
    product_idx = headers.index("产品")

    output = [headers]
    for row_num, original_row in enumerate(input_rows[1:], 1):
        row = list(original_row) + [""] * (len(headers) - len(original_row))
        title = row[title_idx]
        url = row[url_idx]
        try:
            body = fetch_article_body(url, timeout)
            product = match_products(title, body, rules)
            print(f"{row_num:02d}. ok body={len(body)} product={product or '-'} title={title}")
        except (HTTPError, URLError, TimeoutError, OSError) as exc:
            body = f"[抓取失败] {exc}"
            product = ""
            print(f"{row_num:02d}. failed title={title}: {exc}")
        row[body_idx] = body
        row[product_idx] = product
        output.append(row)
        time.sleep(sleep_seconds)
    return output


def validate_xlsx(path: Path, expected_rows: int) -> None:
    with zipfile.ZipFile(path) as workbook:
        sheet = workbook.read("xl/worksheets/sheet1.xml").decode("utf-8")
    actual_rows = sheet.count("<row ")
    if actual_rows != expected_rows:
        raise RuntimeError(f"{path.name}: expected {expected_rows} rows, got {actual_rows}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Enrich WeChat article XLSX with body text and product matches.")
    parser.add_argument("--input", default=DEFAULT_INPUT, help="Input XLSX path.")
    parser.add_argument("--products", default=DEFAULT_PRODUCTS, help="Product knowledge-base CSV path.")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output XLSX path.")
    parser.add_argument("--timeout", type=int, default=25, help="HTTP timeout in seconds.")
    parser.add_argument("--sleep", type=float, default=0.4, help="Pause between article requests.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = Path(args.input)
    products_path = Path(args.products)
    output_path = Path(args.output)

    input_rows = read_xlsx(input_path)
    rules = load_product_rules(products_path)
    enriched = enrich_rows(input_rows, rules, args.timeout, args.sleep)
    written = write_xlsx(output_path, enriched)
    validate_xlsx(written, len(enriched))
    matched_count = sum(1 for row in enriched[1:] if row[enriched[0].index("产品")])
    print(f"wrote {written}")
    print(f"rows={len(enriched) - 1}, matched_products={matched_count}")


if __name__ == "__main__":
    main()
